# -*- coding: utf-8 -*-
"""Task:1,17/6/25 phyton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WknMA7F7SyoVSoduwDF8UlYPaumgTiia
"""

v = 5  #variable declartion
v

id(v) #id addess of memory location that v stored

5 =  v #1variable doesnot starts with numbers, but ends with numbers

1v = 9

v1 = 5
v1

v2 = 10 #2case sensitive
V2

v2 = 10
v2 # case sensetive

r@ =  78
r@  #3r is variable, special character is not allowed

v* = 78
v*      #special character is not allowed in variable

v_ = 10 #4only underscore is allowed in variable
v_

if a = 10

import keyword #reserved words pop up, machine gives automatically
keyword.kwlist

len(keyword.kwlist) # 5,35 keywords are there , can't defined as variable

else = 6

ELSE = 6
ELSE #case

For = 90
FOR #give as given as input

For = 3 #variable = identifier = object
For



spam = 1

2 + 2

50 - 2*5

prefix = "py"
prefix = "thon"

'py' + 'prefix'



